name = "MyOptimizationAlg"
uuid = "595730de-e1dd-4f43-8708-12c2309ca628"
authors = ["mr <maciej_rys@o2.pl>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
BenchmarkTools = "1.6.0"
LinearAlgebra = "1.11.0"
Roots = "2.2.4"
